C  SUBROUTINE CALCULATES AVERAGE SNOW TEMPERATURE
C
      SUBROUTINE SNOWT(SH,DS,WE,SLIQ,TA,DTA,TSNOW,DHC)

C  SPECIFIC HEAT CAPACITIES OF ICE, WATER, AND AIR
      PARAMETER (CICE=2.1E06,CH2O=4.2E06,CAIR=1E03)
C  HEAT WAVE LENGTH, IN SECONDS
      PARAMETER (WAVEL=43200)      

       SHX=0.01*SH
       DHCX=0.01*DHC
       STOT=WE+SLIQ
       DST=0.1*STOT/SH 
       SL=0.0442*EXP(5.181*DST)
       FL=SLIQ/STOT
       SC=CICE*DS+CAIR*(1.-DS-FL)+CH2O*FL
       ALP=SQRT(3.14*SC/(WAVEL*SL))
       IF(DHC .GT. 0.) THEN
        TSNOW=TSNOW+DTA*((EXP(-ALP*DHCX)-EXP(-ALP*SHX))/
     +        (ALP*(SHX-DHCX)))
       ELSE
        TSNOW=TSNOW+DTA*((1.-EXP(-ALP*SHX))/(ALP*SHX))
       ENDIF 
      IF(TSNOW .GT. 0.) TSNOW=0.
      
      RETURN
      END

