C MEMBER UPDT19
C  (from old member FCPACK19)
C
      SUBROUTINE UPDT19(OWE,OSC,TWE,COVER,IUPWE,IUPSC,
     1  WETOL,SCTOL,SI,ADC)
C.......................................
C     THIS SUBROUTINE UPDATES WATER-EQUIVALENT AND SNOW COVER
C       BASED ON OBSERVATIONS.  AFFECTED CARRYOVER VALUES ARE
C       ADJUSTED.
C.......................................
C     SUBROUTINE WRITTEN BY....
C           ERIC ANDERSON - HRL - DECEMBER 1982

CVK        MODIFIED 4/00 BY V. KOREN: TWO NEW STATES ADDED
C.......................................
      DIMENSION ADC(11)
C
C     COMMON BLOCKS
C      COMMON/IONUM/IN,IPR,IPU
      COMMON/SNCO19/WE,NEGHS,LIQW,TINDEX,ACCMAX,SB,SBAESC,SBWS,

CVK   SNDPT & SNTMP STATES ADDED
CVK     1 STORGE,AEADJ,NEXLAG,EXLAG(7)
     1 STORGE,AEADJ,NEXLAG,EXLAG(7),SNDPT,SNTMP
C.......................................
C
C     UPDATE WATER-EQUIVALENT FIRST IF OBSERVED WE AVAILABLE.
      IF(OWE.LT.0.0) GO TO 250
      IF(IUPWE.EQ.0) GO TO 250
      IF(OWE.LT.1.0) OWE=0.0
C
C     UPDATE WE IF DIFFERENCE EXCEEDS TOLERANCE.
      IF(ABS(OWE-TWE).LE.(WETOL*TWE)) GO TO 250
      TWE=OWE
C
C     UPDATE CARRYOVER VALUES TO BE CONSISTENT WITH THIS CHANGE.
      IF(TWE.GT.0.0) GO TO 235
C
C     NO SNOW REMAINS AFTER UPDATE - CANNOT UPDATE AREAL SNOW
C        COVER EVEN IF OBSERVED VALUE EXISTS.
      CALL ZERO19
      COVER=0.0
      GO TO 290
C
C     ADJUST CARRYOVER VALUES BASED ON NEW WATER-EQUIVALENT.
  235 CALL ADJC19(TWE,SI,ADC)
C
C     COMPUTE AREAL EXTENT OF SNOW BASED ON NEW WE.
      CALL AESC19(WE,LIQW,ACCMAX,SB,SBAESC,SBWS,SI,ADC,AEADJ,COVER)
C
C     UPDATE AREAL EXTENT OF SNOW-COVER IF OBSERVED AESC AVAILABLE
C         AND A SNOW COVER EXISTS.
  250 IF(OSC.LT.0.0) GO TO 290
      IF(IUPSC.EQ.0) GO TO 290
      IF (TWE.LT.0.1) GO TO 290
C
C     UPDATE AESC IF DIFFERENCE EXCEEDS TOLERANCE - ALSO CHANGE AEADJ.
      IF(ABS(OSC-COVER).LE.SCTOL) GO TO 290
      IF(OSC.GT.0.05) GO TO 260
      IF(OSC.EQ.0.0) GO TO 255
C      WRITE(IPR,907)
C  907 FORMAT(1H0,112H**WARNING** AREAL EXTENT OF SNOW IS NOT UPDATED FOR
C     1 OBSERVED AREAL EXTENT VALUES IN THE RANGE GT 0.0 TO LE 0.05.)
C      CALL WARN
      GO TO 290
C
C     NO SNOW REMAINS
  255 CALL ZERO19
      COVER=0.0
      TWE=0.0
      GO TO 290
C
C     ADJUST CARRYOVER FOR OBS. AREAL EXTENT.
  260 IF(OSC.GT.1.0) OSC=1.0
      COVER=OSC
      CALL AECO19 (COVER,TWE,SI,ADC)
C     ALL UPDATING COMPLETED.
C.......................................
 290  RETURN
      END

